default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
