# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe7cf878cd54640371ee9ac17cf0f0eb67a568ad04f28fe7bf4791748dc077806cc755dd7331f28d3ec9cf5ab6f0fd4713fdc06708d3b3f1476c6ca720ac536

test:
  secret_key_base: 9c65cea45e8140a15815b9694e2a961d0a7813d57dc40e1e5fb32aced7b8d9a347a7538d784c5246019311a224e4b01a9c34c8a4bd1e6954bc2ab90205f2c97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
